A brand 1 = 
var ratea = IF (
        CALCULATE(SUM ( '1-Sales Details'[QTY] ),ALL('1-Sales Details'[Actual staff1])) >= SUM ( 'Commission Target'[A Target] ),
         50,
         40
    )
return

CALCULATE (
    
        SUM ( '1-Sales Details'[QTY] ) * ratea
    ,
    FILTER ( ECORESCATEGORY, ECORESCATEGORY[NAME] = "A" ),
    FILTER ( '1-Sales Details', '1-Sales Details'[NETAMOUNT] > 100 )
)
    + CALCULATE (
        SUM ( '1-Sales Details'[QTY] ) * ratea,
        FILTER ( ECORESCATEGORY, ECORESCATEGORY[NAME] = "A" ),
        FILTER ( '1-Sales Details', '1-Sales Details'[NETAMOUNT] < 0 )
    )
